export const exportedColumns = [
    {
        field: "id_employee",
        headerName: "ID",
        width: 90,
        align: "center",
        headerAlign: "center",
      },
      {
        field: "first_name",
        headerName: "First name",
        width: 150,
        editable: false,
        align: "center",
        headerAlign: "center",
      },
      {
        field: "last_name",
        headerName: "Last name",
        width: 150,
        editable: false,
        align: "center",
        headerAlign: "center",
      },
      {
        field: "cuit",
        headerName: "cuit",
        width: 150,
        editable: false,
        align: "center",
        headerAlign: "center",
      },
      {
        field: "team_id",
        headerName: "team_id",
        width: 150,
        editable: false,
        align: "center",
        headerAlign: "center",
      },
      {
        field: "join_date",
        headerName: "join_date",
        width: 150,
        editable: false,
        align: "center",
        headerAlign: "center",
      },
      {
        field: "rol",
        headerName: "rol",
        width: 150,
        editable: false,
        align: "center",
        headerAlign: "center",
      },
]
