export const exportedColumns = [
    {
        field: "id_asset",
        headerName: "ID",
        width: 90,
        align: "center",
        headerAlign: "center",
      },
      {
        field: "name",
        headerName: "Name",
        width: 150,
        editable: false,
        align: "center",
        headerAlign: "center",
      },
      {
        field: "type",
        headerName: "Type",
        width: 150,
        editable: false,
        align: "center",
        headerAlign: "center",
      },
      {
        field: "code",
        headerName: "Code",
        width: 150,
        editable: false,
        align: "center",
        headerAlign: "center",
      },
      {
        field: "marca",
        headerName: "marca",
        width: 150,
        editable: false,
        align: "center",
        headerAlign: "center",
      },
      {
        field: "description",
        headerName: "Description",
        width: 150,
        editable: false,
        align: "center",
        headerAlign: "center",
      },
      {
        field: "purchase_date",
        headerName: "purchase_date",
        width: 150,
        editable: false,
        align: "center",
        headerAlign: "center",
      },
      {
        field: "id_employee",
        headerName: "id_employee",
        width: 150,
        editable: false,
        align: "center",
        headerAlign: "center",
      },
]
